### ISSUE TITLE
任务条件达成时不变色

### ISSUE THREAD

**Issue by cxqclz** [TimChen44/KSP_zh#104]
正在测试

**Comment by cxqclz** [comment]
经测试与zh.xml汉化无关

**Comment by cxqclz** [comment]
艹，图片怎么传不上来了？
纯英文的任务条件达成时前面有一个绿色的勾，汉化后没有，且与zh.xml无关，请程序猿@Timchen44 检查解决……

**Comment by cxqclz** [comment]
艹，图片怎么传不上来了？
纯英文的任务条件达成时前面有一个绿色的勾，汉化后没有，且与zh.xml无关，请程序猿@Timchen44 检查解决……

**Comment by pitwam** [comment]
我把zhFont.xml这个字体文件内容删除能显示，是不是中文字体中没有这些符号？
![360 20150824170928104](https://cloud.githubusercontent.com/assets/12621656/9458291/48ea3488-4b1f-11e5-85fc-665cb0f5cb77.jpg)
![360 20150825102151184](https://cloud.githubusercontent.com/assets/12621656/9458292/4a0239e2-4b1f-11e5-9992-fca1514891b1.jpg)

**Comment by cxqclz** [comment]
有可能，这个要问@Timchen44  ，不过，1.1版本快来了，升级unity5引擎，汉化部分改区域化了，老版本的现在都不用去研究了，等新版本来了再说吧

**Comment by pitwam** [comment]
嗯

**Comment by TimChen44** [comment]
版本更迭，所有问题关闭。
