### ISSUE TITLE
MAC OS 中文字消失

### ISSUE THREAD

**Issue by pcggsyz** [TimChen44/KSP_zh#11]
在MAC平台下安装汉化后游戏内文字全都看不见了

**Comment by TimChen44** [comment]
不支持MAC平台

**Comment by TimChen44** [comment]
我没有mac电脑，所以没法做支持mac的汉化补丁T_T

**Comment by zanderzhng** [comment]
@pcggsyz 你确认下你安装步骤对不对。我这是没问题的。

**Comment by zanderzhng** [comment]
先确认游戏版本是，v1.0.2.842。下载0.3的release，解压后你应该能看到三个文件夹。
├── GameData
├── KSP_Data
└── saves

1.把GameData文件夹里的DTS_Addon.dll与DTS_zh文件夹放到游戏目录里的GameData文件夹下。

2.对游戏目录下的KSP.app点右键，选这个显示包的内容。
![screen shot 2015-05-09 at 0 20 55](https://cloud.githubusercontent.com/assets/867749/7539352/5b1e18e2-f5e1-11e4-9b9b-52acd6927766.png)
然后备份好KSP.app/Contents/Data/Managed/Assembly-CSharp.dll，把解压缩出来的KSP_Data里边的Assembly-CSharp.dll和DTS_zh.dll放到KSP.app里边。

3.saves换不换问题不大。

**Comment by zanderzhng** [comment]
![screen shot 2015-05-09 at 0 28 09](https://cloud.githubusercontent.com/assets/867749/7539490/4c5f5676-f5e2-11e4-849f-0cddbf11dde1.png)

**Comment by zanderzhng** [comment]
@TimChen44 我周末写个自动安装的脚本吧。现在这个替换游戏Assembly-CSharp.dll的方法无论如何避不开么。用Module Manager之类的？

**Comment by TimChen44** [comment]
无法用插件避免，当然现在不踢换Assembly-CSharp.dll汉化程序依旧可以工作，只是zh.xml中的汉化条目无法被加载，其他内容均可正常使用。现在大家翻译的文本就是通过类似Module Manager的模式加进去的。

**Comment by zanderzhng** [comment]
那能不能用ModuleManager不用那个DTS_Addon.dll呢，能少一个插件少一个插件吧。

**Comment by pcggsyz** [comment]
重置了几次游戏以后已经可以顺利工作了。。。不过这游戏在MAC上真的是裸奔的好不顺畅，总是出错= =

**Comment by zanderzhng** [comment]
@pcggsyz mac下ksp开高材质高渲染，内存占用超过2.2G了就容易跳出。0.2x开始就这样了。

**Comment by pcggsyz** [comment]
@zanderzhng 顶配的MBP真是欲哭无泪，所以全效最低就能规避这个问题了么？

**Comment by zanderzhng** [comment]
是的。等官方修复吧。换unity5支持64bit了应该就好了。

**Comment by TimChen44** [comment]
@zanderzhng 那个DTS_Addon.dll除了完成ModuleManager能完成的一些资源汉化外，还有显示汉字，组件右键操作栏汉化，一些提示框汉化，游戏开始菜单汉化等，如果用他那就多一个插件了，只是当时选择用xml有点后悔，配置文件语法有点啰嗦，以后空了改成和KSP配置一样的语法。
