### ISSUE TITLE
空间站对接后 断开对接失灵

### ISSUE THREAD

**Issue by shami230** [TimChen44/KSP_zh#112]
我在一次对接后 不满意按了F5保存 然后断开对接 当时是断开了 但是我发现控制不在需要调整飞船 返回雷达麻烦 于是F9 然后选择控制调整的飞船 再次断开 这个时候断开势力了 重启游戏也没法断开  玩的沙盒模式！

**Comment by cxqclz** [comment]
谢谢@pitwam，下个版本出来要做个清洁版，把不确定的通通都删掉，有不全再补，回头功做的太多了

**Comment by pitwam** [comment]
不用谢的 @cxqclz ，只是做了一些力所能及的事，觉得能给汉化添砖加瓦看着插件一天天完善，能参与其中挺有意思的。
