### ISSUE TITLE
建造模式中载入飞船略图显示的问题

### ISSUE THREAD

**Issue by pitwam** [TimChen44/KSP_zh#118]
如果新建游戏有中文或飞船存储时用了中文，只要任意一个用了中文，载入飞船的略图都显示为一个火箭的图标，没有用中文显示正常。
![360 20150716114441480](https://cloud.githubusercontent.com/assets/12621656/8715228/fd4d6118-2bb0-11e5-9cef-97da3d485fcf.jpg)
![360 20150716114552778](https://cloud.githubusercontent.com/assets/12621656/8715229/fd535000-2bb0-11e5-96a2-d60d0309d13e.jpg)

**Comment by TimChen44** [comment]
版本更迭，所有问题关闭。
