### ISSUE TITLE
mac steam 下载的游戏，能不能汉化？ 

### ISSUE THREAD

**Issue by ppo279** [TimChen44/KSP_zh#120]
我在Mac steam下，下载了最新版的 ksp 1.0.4 , 
 游戏根目录下，没有GameData、KSP_Data、saves三个文件夹。

**Comment by cxqclz** [comment]
吾等穷鬼，买不起imac

**Comment by TimChen44** [comment]
吾等穷鬼，买不起imac

**Comment by jiangtiandao** [comment]
吾等穷鬼，买不起imac

**Comment by AZLisme** [comment]
答案是可以，但是可能没有Win下完美。
+GameData
这是Mod文件夹，如果你没装Mod的话，是没有的。直接根目录新建即可。

+KSP_Data
这个和Win不同，你要在KSP的软件包上右键，显示包内容，在Contents/Data/Managed文件夹下，把KSP_Data里面的 Managed文件拷贝覆盖进去，注意Mac不要直接覆盖文件夹。

+Saves
也没有的话，就直接根目录新建就行

**Comment by AZLisme** [comment]
答案是可以，但是可能没有Win下完美。
+GameData
这是Mod文件夹，如果你没装Mod的话，是没有的。直接根目录新建即可。

+KSP_Data
这个和Win不同，你要在KSP的软件包上右键，显示包内容，在Contents/Data/Managed文件夹下，把KSP_Data里面的 Managed文件拷贝覆盖进去，注意Mac不要直接覆盖文件夹。

+Saves
也没有的话，就直接根目录新建就行

**Comment by AZLisme** [comment]
答案是可以，但是可能没有Win下完美。
+GameData
这是Mod文件夹，如果你没装Mod的话，是没有的。直接根目录新建即可。

+KSP_Data
这个和Win不同，你要在KSP的软件包上右键，显示包内容，在Contents/Data/Managed文件夹下，把KSP_Data里面的 Managed文件拷贝覆盖进去，注意Mac不要直接覆盖文件夹。

+Saves
也没有的话，就直接根目录新建就行

**Comment by jiangtiandao** [comment]
测试过吗？
@AZLisme

**Comment by TimChen44** [comment]
版本更迭，所有问题关闭。
