### ISSUE TITLE
汉化后kAS和KIS无法使用

### ISSUE THREAD

**Issue by qq392046** [TimChen44/KSP_zh#122]
汉化后kAS和KIS无法使用，会缺失配件

**Comment by qq392046** [comment]
我把原版的Assembly-CSharp.dll文件替换你的汉化包，暂时解决配件消失的问题
还在测试看看有没别的问题

**Comment by pitwam** [comment]
请确定你的游戏版本是不是1.0.4

**Comment by pitwam** [comment]
如果 @qq392046  你的是1.0.2版本就下载0.13的汉化包，
看这里https://github.com/TimChen44/KSP_zh/releases

**Comment by qq392046** [comment]
我的游戏版本是v1.0.4.861，我确认。
正确的应该是KAS部件缺失，而kis正常。

**Comment by qq392046** [comment]
在科技术有显示，但在组装车间消失

**Comment by pitwam** [comment]
@qq392046 具体消失的情况贴个图看看。我这里都显示正常。

**Comment by qq392046** [comment]
哦，上面说错了，是kis消失，kas正常。
前面3张是正常情况，后面2张就是用你汉化的，会丢失分类
我截图了，在http://xiangce.baidu.com/picture/detail/ccd18979fa259c63dae96e7630e15700b4daa964

**Comment by pitwam** [comment]
哦，我没装KIS MOD，这里的汉化文件只针对原版文件汉化，具体问一下 @TimChen44

**Comment by qq392046** [comment]
问题是针对原版汉化后，改变了本身的结构。。。
又有几个不用MOD的玩家？

**Comment by pitwam** [comment]
用原版测试能正常显示，其他未有试
![360 20150803144436039](https://cloud.githubusercontent.com/assets/12621656/9032665/7513077a-39f3-11e5-8808-70bbe0e2cacb.jpg)
