### ISSUE TITLE
请问1.04的补丁支持1.1吗？

### ISSUE THREAD

**Issue by pcggsyz** [TimChen44/KSP_zh#135]
今天打开STEAM一看已经更新到了1.1了，貌似是用了新的引擎，不知道旧补丁能不能用呢？

**Comment by TimChen44** [comment]
啊，升级了？1.1了？我能说我都不知道么:P

不好意思，明确的告诉你不支持，据说1.1支持多国语言了，本人还没研究过，不能下太多结论。
