### ISSUE TITLE
能增加kOS 的汉化支持吗

### ISSUE THREAD

**Issue by q349980363** [TimChen44/KSP_zh#136]
http://forum.kerbalspaceprogram.com/threads/68089-0-23-kOS-Scriptable-Autopilot-System-v0-11-2-13

**Comment by q349980363** [comment]
![default](https://cloud.githubusercontent.com/assets/4111244/10415233/1ba9b646-7023-11e5-8c9a-19a769bc98c2.png)

**Comment by TimChen44** [comment]
版本更迭，所有问题关闭。
