### ISSUE TITLE
打了汉化补丁游戏出错

### ISSUE THREAD

**Issue by AndongDu** [TimChen44/KSP_zh#143]
![1458592479054](https://cloud.githubusercontent.com/assets/17992222/13933298/bf07bf14-efac-11e5-845f-a589e100296e.jpg)
我确定我没有错补丁和游戏版本，补丁：0. 18 游戏：1.0.5.1024

**Comment by jiangtiandao** [comment]
@AndongDu  1.0.5.1028使用正常  请升级版本与steam最新版同步
