### ISSUE TITLE
游戏汉化不完整

### ISSUE THREAD

**Issue by malow005** [TimChen44/KSP_zh#166]
win10系统，steam正版游戏版本号v1.1.3.1289，没有装mod，安装汉化之后主页面菜单和部件有汉化，设置部分没有汉化

**Comment by leikaiwei** [comment]
同样, 1.1.3.1289

刚入正.. 又庆幸找到组织.. 但是覆盖汉化文件后 只有menu是中文的

选项 及游戏里面 部分中文 部分英文..  (大多数还是英文)

环境win10

游戏32  64 都试过 一样的问题  求帮助....
