### ISSUE TITLE
1.1.3适合MAC吗？

### ISSUE THREAD

**Issue by yyyyyyx** [TimChen44/KSP_zh#167]
steam 正版 1.1.3 安装后无法显示任何组件 地面贴图也不完整

**Comment by jiangtiandao** [comment]
@yyyyyyx   汉化通过修改游戏程序实现 不支持MAC

**Comment by yyyyyyx** [comment]
@jiangtiandao  果然  最近我太忙了 过一阵看看有没有时间研究下mac的汉化  贴吧mac党也很多呢 多谢： ）

**Comment by jiangtiandao** [comment]
@yyyyyyx     我看了一下mac版本文件  要修改的DLL是一样的  理论上可以支持  可能是Mac的KSP路径和Win不一样导致替换失败&加载不了汉化词条  比如要修改的 DLL在Mac下路径是 /KSP.app/Contents/Data/Managed/Assembly-CSharp.dll    Win下是 KSP_Data\Managed\Assembly-CSharp.dll  
能提供一下KSP.log

**Comment by yeliex** [comment]
https://gist.github.com/yeliex/a7c015840261bd60253c5b59b24526bb
@jiangtiandao @TimChen44

**Comment by TimChen44** [comment]
@yeliex 
游戏就是用Unity3D开发的，他用的的确是Mono，只是我没有时间去研究mac，等有mac电脑的高手来处理了。

**Comment by yeliex** [comment]
能不能修改下路径直接编译一份出来 我这边没有vs开发环境

**Comment by jiangtiandao** [comment]
@yeliex   64位dll一样的 32位的不一样 
不能直接用Win的补丁主要是因为依赖Windows的路径  dll没有覆盖成功
32位 dll 路径分别是
Mac ： \KSP.app\Contents\Data\Managed\Assembly-CSharp.dll  
Win  ：\KSP_Data\Managed\Assembly-CSharp.dll
64位 dll 路径分别是
Mac：  \KSP.app\Contents\Resources\Data\Managed\Assembly-CSharp.dll
Win：   \KSP_x64_Data\Managed\Assembly-CSharp.dll
还有就是读取汉化文件 依赖GameData的路径  不知道MAC下的GameData在哪里 怎么访问
你先把那两个dll或者64位的dll按照正确路径覆盖了  补丁里GameData里的内容复制进Mac的GameData
看看能用不

**Comment by yeliex** [comment]
@jiangtiandao 直接使用了64位的Assembly-CSharp.dll覆盖以后 加载运行文本显示了文本ID 所以应该是找不到GameData,GameData不知道是怎样一个寻址逻辑 我放到了\KSP.app\Contents\下面 实际上GameData的路径在KSP.app所在的目录下面

**Comment by jiangtiandao** [comment]
@yeliex  补丁的GameData文件放了没？

**Comment by jiangtiandao** [comment]
@yeliex
我觉得应该放到KSP.app  下面 MAC下原来GameData在哪里 就应该放到哪里
寻址是这样的
document.Load(File.OpenRead("GameData/DTS_zh/zh_x64.xml"));

**Comment by yeliex** [comment]
正常工作 我可以PR一个OSX下面的一键部署包

**Comment by yeliex** [comment]
部分翻译不全

**Comment by jiangtiandao** [comment]
@yeliex  设置的文本翻译了 但是没有加载

**Comment by profoundeye** [comment]
@yeliex 你部署成功了吗？比如你说的：
64位 dll 路径分别是
Mac： \KSP.app\Contents\Resources\Data\Managed\Assembly-CSharp.dll
这个文件，我在本机没有找到，太奇怪了。

**Comment by profoundeye** [comment]
@jiangtiandao 无法按照上面的描述来做，我就没找到他说的这些文件。。。。

**Comment by profoundeye** [comment]
抱歉，我找到问题所在了。
1 将补丁文件中的：Mac： \KSP.app\Contents\Resources\Data\Managed\Assembly-CSharp.dll 替换为补丁中的 Assembly-CSharp.dll 
2 将 补丁中的GameData覆盖文件目录下的GameData
然后变成中文了，而且任务，模块会变成中文。

尚未变成中文的地方：

1. 进入游戏后的基地主画面，各建筑描述。
2. 部件描述，部分是中文部分不是
3. 任务描述是中文，但是任务条件不是中文。
