### ISSUE TITLE
有个bug

### ISSUE THREAD

**Issue by chirunosw** [TimChen44/KSP_zh#169]
okto探测器核心在科技大楼里电力解锁那一级右侧栏会显示n多个，火箭大楼里okto核心随机出现汉化的和没汉化的说明，不能发射

**Comment by chirunosw** [comment]
额，okto核心的问题太大了，出现了各种非自然现象，希望改进

**Comment by pitwam** [comment]
我在32位的生涯模式没有出现这个“显示N多个OKTO核心”，另外科技大楼里解锁的是OKTO2代。火箭装配大楼安装OKTO能发射，也没有发现会有未汉化的说明出现。请问你用的是64位吗？是生涯模式还是科技模式？

**Comment by chirunosw** [comment]
嗯是64位，科研模式，解锁了之后装配大楼里使用的话会显示未解锁，然后不知道怎么回事科研中心okto核心那一块就出现n多个，偶尔火箭装配大楼里okto核心变成了英文的就又正常了，但是回来改火箭再发射就又提示未解锁，抱歉之前忘了回复你

**Comment by jiangtiandao** [comment]
我在64位科研模式下测试无问题  请压缩上传存档和KSP安装文件夹下的KSP.log文件 方便定位问题
@chirunosw
