### ISSUE TITLE
win10   v1.1.3.1289  汉化不完整 求帮助

### ISSUE THREAD

**Issue by leikaiwei** [TimChen44/KSP_zh#176]
新开一个.. 以突出问题.. (搜遍贴吧 论坛 怎么就没人反映过? 难道是个例? 我的台式机和笔记本都是这个问题)  台式机笔记本环境一样...

同上 1.1.3.1289 版本  win10环境.. 

刚入正.. 又庆幸找到组织.. 但是覆盖汉化文件后 只有menu是中文的

选项 及游戏里面 部分中文 部分英文.. (大多数还是英文)

游戏32 64 都试过 一样的问题 求帮助....

**Comment by leikaiwei** [comment]
@jiangtiandao  有什么需要我提供的信息。。 我都会尽量配合的。。多谢大哥了。。

**Comment by jiangtiandao** [comment]
具体是哪里没有翻译呢？ 最好截个图

**Comment by gc313** [comment]
感谢大家的工作！

**Comment by leikaiwei** [comment]
http://i1.buimg.com/567571/bbeb2917f66626aa.png
http://i1.buimg.com/567571/821386e06f940b98.png
http://i1.buimg.com/567571/48a44e3a9e92d2ae.png
http://i1.buimg.com/567571/39fbbbb89ade5d79.png

@jiangtiandao 网速不太好, 用了别的地方的图床..您看下..

游戏版本之类的都是对应的 但是效果就是这样 大部分都是英文..

**Comment by jiangtiandao** [comment]
@leikaiwei  Sandbox 那三个翻译了会有bug

**Comment by leikaiwei** [comment]
@jiangtiandao   那个地方倒是无伤大雅..  主要是游戏内容把.. 比如建筑物的名字 描述..  选项设置等等..

我也是第一次玩这游戏..

**Comment by leikaiwei** [comment]
因为看你们的截图 都是OK的.. 所以不知道是我的环境问题 还是什么...

**Comment by leikaiwei** [comment]
另外我也是搞C#的.. 所以开发环境也都有..  如果需要远程或调试看看什么的话  我也随时乐意配合..  我的企鹅443947595

**Comment by jiangtiandao** [comment]
@leikaiwei  那个截图是旧版本过时了

**Comment by leikaiwei** [comment]
@jiangtiandao  原来如此，那就是目前1.1.3的只能是这样喽。。 那好把。。

感谢你们啦。。 加油。。 能将新版变成都那样就好了。。
