### ISSUE TITLE
mac下不能运行

### ISSUE THREAD

**Issue by profoundeye** [TimChen44/KSP_zh#183]
您好：
非常感谢您对坎巴拉太空计划的翻译
我是osx 的系统，坎巴拉steam版本号：1.1.3.1289。在复制文件之后，进入游戏之后，选择生涯模式，发现火箭组件为空，任务为空。在菜单中，训练教程也是空的。
可能是bug，反馈给您。
再次感谢您的翻译。
附件中是日志文件。
[KSP.log.zip](https://github.com/TimChen44/KSP_zh/files/504321/KSP.log.zip)

**Comment by jiangtiandao** [comment]
#167
