### ISSUE TITLE
1.2更新之后汉化方法失效

### ISSUE THREAD

**Issue by jiangtiandao** [TimChen44/KSP_zh#184]
- [x] BUG或其他
### 异常情况描述

SpriteTextRich 直接没了源码编译不能  直接用旧的binary的话就就报错
@TimChen44 
### 日志文件链接

[ERR 22:56:03.417] AssemblyLoader: Exception loading 'DTS_Addon': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 

Additional information about this exception:

 System.TypeLoadException: Could not load type 'DTS_Addon.xFont' from assembly 'DTS_Addon, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'Font2Font' from assembly 'DTS_Addon, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by jiangtiandao** [comment]
http://blog.csdn.net/yuxikuo_1/article/details/45506185

1.3 字符采用  Text Mesh Pro 显示

**Comment by profoundeye** [comment]
关注。
感谢大大

**Comment by AZLisme** [comment]
确实，1.2版本更新后没有办法进入游戏了，希望能够尽快修复！感谢大神

**Comment by zapline** [comment]
关注。
感谢大大
