### ISSUE TITLE
[问题]如何在非windows愉快玩耍+似乎有新版本了

### ISSUE THREAD

**Issue by indoorsNB** [TimChen44/KSP_zh#188]
还有readme.md没更新

**Comment by indoorsNB** [comment]
dalao在吗

**Comment by jiangtiandao** [comment]
这个补丁修改了dll而非win程序路径不同  需要自己找到对应文件覆盖
Mac 参见另一个issue #167    Linux下路径似乎和Windows一样
@indoorsNB

**Comment by indoorsNB** [comment]
原来如此：P
