### ISSUE TITLE
目前版本翻译导致主菜单除新游戏之外无法点击

### ISSUE THREAD

**Issue by jiangtiandao** [TimChen44/KSP_zh#19]
而0.4发布版本正常

**Comment by TimChen44** [comment]
现在人手紧张，您能不能帮我做一些BUG的定位？操作很简单，就是用记事本打开zh.xml文件，然后删除下面连接中被翻译的条目（正行删除），当删除那个条目后BUG消失了，就请你把这个条目告诉我，万分感谢。
https://github.com/TimChen44/KSP_zh/commit/7e881711c6df3ff7713907e8a7d2b451990dfacc
https://github.com/TimChen44/KSP_zh/commit/9160efc20c8b70e6b24c071b6d56c8c496cccf3b

**Comment by TimChen44** [comment]
现在人手紧张，您能不能帮我做一些BUG的定位？操作很简单，就是用记事本打开zh.xml文件，然后删除下面连接中被翻译的条目（整行删除），当删除那个条目后BUG消失了，就请你把这个条目告诉我，万分感谢。
https://github.com/TimChen44/KSP_zh/commit/7e881711c6df3ff7713907e8a7d2b451990dfacc

https://github.com/TimChen44/KSP_zh/commit/9160efc20c8b70e6b24c071b6d56c8c496cccf3b

**Comment by jiangtiandao** [comment]
我自己搞了一下午这个工作，其实不用难么难。看KSP.log
瞬间定位

**Comment by TimChen44** [comment]
对的，最好按照游戏中出现的内容翻译。一般来说比较长的一句话不太可能会有问题。

**Comment by jiangtiandao** [comment]
然而没有完全修复  继续游戏还是不能点击 
将zh.xml 替换为 en.xml之后bug仍然存在 考虑其他因素。
日志里面是这一句话
[EXC 01:18:06.039] NullReferenceException: Object reference not set to an instance of an object
	KerbalRoster.SetExperienceTrait (.ProtoCrewMember pcm, System.String traitName)
	ProtoCrewMember..ctor (Modes mode, .ConfigNode node, KerbalType crewType)
	KerbalRoster..ctor (.ConfigNode node, Modes mode)
	Game..ctor (.ConfigNode root)
	GamePersistence.LoadGame (System.String filename, System.String saveFolder, Boolean haltIfIncompatible, Boolean suppressErrorMessage)
	MainMenu.LoadGame ()
	TextButton3D+
