### ISSUE TITLE
最新版本对1.21乱码(64位)

### ISSUE THREAD

**Issue by MrJr44** [TimChen44/KSP_zh#190]
系统是64位Win10的，下载了汉化包(64位)就找到游戏根目录安装了。然后我启动KSP_x64.exe之后只有Tips和Text以及Version三个英文。换成KSP.exe之后可以正常进入主页面，但是进入游戏之后部分文字变成类似于‘口’的字。这个是BUG吗????????????????????????????????????????????????????????????????????????????

**Comment by haoliang968** [comment]
不是，不知道是什么版本开始，KSP官方把字库换了，然后这些显示“口”的汉字显示不出来。也是现在汉化遇到最大的困难吧，我汉化MOD现在都不敢动了，一些文字都显示不出来还不如不汉化。。。重要的事如何把官方字体库变回原来的？这是关键！

**Comment by MrJr44** [comment]
能不能替换一下原版字库?看看有没有类似于font的东西。。
