### ISSUE TITLE
官方准备中文翻译了，有合并意向吗？

### ISSUE THREAD

**Issue by Sefank** [TimChen44/KSP_zh#194]
好像丝瓜德要出中文了，这个翻译会提供给官方吗？
参考链接：
http://forum.kerbalspaceprogram.com/index.php?/topic/154614-ksp-weekly-we%E2%80%99re-back/
http://forum.kerbalspaceprogram.com/index.php?/topic/154964-ksp-weekly-volunteers-wanted/

**Comment by TimChen44** [comment]
如果官方翻译当然好啦。这个翻译本身就是开源的，官方想要拿去就行的。不知道官方有没有中文版的计划。
