### ISSUE TITLE
无法使用鼠标滚轮，不能点击“继续游戏”读档

### ISSUE THREAD

**Issue by jiangtiandao** [TimChen44/KSP_zh#21]
描述： 任何场景内（IVA EVA map 第三人称）均无法使用鼠标滚轮进行缩放
点击开始游戏，弹出菜单中点击继续游戏无反应

尝试去除所有翻译均无法消除bug，判断可能是程序原因，log定位如下。
[EXC 02:05:59.148] NullReferenceException: Object reference not set to an instance of an object
	KerbalRoster.SetExperienceTrait (.ProtoCrewMember pcm, System.String traitName)
ProtoCrewMember..ctor (Modes mode, .ConfigNode node, KerbalType crewType)
KerbalRoster..ctor (.ConfigNode node, Modes mode)
Game..ctor (.ConfigNode root)
GamePersistence.LoadGame (System.String filename, System.String saveFolder, Boolean haltIfIncompatible, Boolean suppressErrorMessage)
MainMenu.LoadGame ()
TextButton3D+
.MoveNext ()

**Comment by TimChen44** [comment]
你吧汉化补丁的dts_addon也去掉看看有没有问题

**Comment by TimChen44** [comment]
多汉化了<string id="566"><![CDATA[name]]></string>词条。
建议一些直邮一个单词的词条不要翻译，这些东西很多都有额外的用途

**Comment by TimChen44** [comment]
无法打开继续游戏是应为多汉化了<![CDATA[name]]>词条。
建议一些直邮一个单词的词条不要翻译，这些东西很多都有额外的用途/
关于鼠标滚轮问题，我用Steam验证了游戏文件完整性后鼠标滚轮功能还是不能用，我真怀疑是不是游戏自身的bug啊。

**Comment by jiangtiandao** [comment]
实测英文原版可以正常使用鼠标滚轮

**Comment by TimChen44** [comment]
因为我这里验证完整性后还不能滚轮，看来要重装，麻烦你可以帮我做这样的测试么。
加上汉化补丁，然后把zh.xml中所有条目删除，看看有没有问题。

**Comment by jiangtiandao** [comment]
航天中心可以使用滚轮其他条件下不行

**Comment by TimChen44** [comment]
已经修复
