### ISSUE TITLE
重大bug

### ISSUE THREAD

**Issue by xccxcs** [TimChen44/KSP_zh#30]
小绿人只显示1个并且不能招聘，
在飞行过程中按M切不回飞行器 坎星贴图消失，且不能控制飞行，
生涯和沙盒都出现这样，版本1.0.2原版什么mod都没有，就打了个汉化

**Comment by xccxcs** [comment]
汉化版本KSP_zh_0.5_1.0.2

**Comment by AZLisme** [comment]
同样遇到这个Bug

**Comment by AZLisme** [comment]
我刚刚自己测试，把Assembly-CSharp.dll换成原版，能够解决问题，同时保留部分中文。
目前而已感觉这样先用着还可以。

**Comment by TimChen44** [comment]
哇，一下子三个问题，话说你把它拆成三个提交多好，到时候一下解决三个问题多有成就感^_^

**Comment by TimChen44** [comment]
@AZLisme 替换Assembly-CSharp.dll就是为了加载zh.xml中的翻译内容，现在出现bug基本都是zh.xml中翻译了不该翻译的词条。

**Comment by AZLisme** [comment]
行，我明白了。
关于招聘的Bug我去把相关词条删除看看。

另外，我可以写一个简单的工具自动安装备份回滚汉化补丁，目前好像没有这个吧？

**Comment by TimChen44** [comment]
如果你时间充裕的话，可以写一个工具，而且文件直接可以连接到这里，这样就相当于一个汉化补丁自动升级的功能了，配合每次升级前备份文件，提供还原，GOOD，完爆游侠&3DM汉化补丁安装机制

**Comment by TimChen44** [comment]
已经修正"小绿人只显示1个并且不能招聘，"问题

**Comment by TimChen44** [comment]
经过测试“在飞行过程中按M切不回飞行器 坎星贴图消失，且不能控制飞行“问题已经不存在了，可能顺带一起修复了。
