### ISSUE TITLE
新游戏 菜单内的 “科研模式”词条冲突

### ISSUE THREAD

**Issue by yybl** [TimChen44/KSP_zh#33]
新游戏菜单上的词条  “科研模式”  会把VAB内的分类筛选  相应的单词 一起汉化了。

**Comment by yybl** [comment]
建议  新游戏  菜单内的游戏模式   不要加入模式2字，分别翻译成  沙盘、科研、生涯

**Comment by jiangtiandao** [comment]
根据 issue #76  该条目不能翻译所以没有必要继续讨论了
