### ISSUE TITLE
组装车间内 按制造商筛选 组件 无法正常筛选

### ISSUE THREAD

**Issue by yybl** [TimChen44/KSP_zh#34]
估计是汉化了 所有组件的制造商引起的。

**Comment by xccxcs** [comment]
我也出现了这个问题 无法选择分类

**Comment by xccxcs** [comment]
这个问题以前是不是出现过啊

**Comment by TimChen44** [comment]
@yybl 还真有可能是喊话了制造商名称，还原两个制造商的汉化试试能不能分类。

**Comment by yybl** [comment]
我试过删除 part.xml内厂家，删除part.xml文件，重启游戏，依然无法按厂家排列。

**Comment by TimChen44** [comment]
有没有试过新开存档呢？

**Comment by yybl** [comment]
确认只要修改了制造商就无法进行筛选，不管是否有中文，使用ModuleManager.2.6.3进行修改也一样。
使用第三方插件也无法现在在内（比如MagicSmokeIndustries）。
只支持原版游戏本身的那些制造商名称。

**Comment by yybl** [comment]
使用ModuleManager 把第三方part改成 原本的制造商名称就可以正常显示。。

**Comment by TimChen44** [comment]
那么看来制造商名字没法通过xSquad中的配置汉化了，看来需要考虑使用zhItem.xml或者zhText.xml来实现汉化了

**Comment by TimChen44** [comment]
版本更迭，所有问题关闭。
