### ISSUE TITLE
汉化后教程第一场景卡在指令仓

### ISSUE THREAD

**Issue by pitwam** [TimChen44/KSP_zh#42]
教程训练的第一个场景，让放置指令仓时左边目录是空的，英文版无问题。

**Comment by jiangtiandao** [comment]
已经修复

**Comment by pitwam** [comment]
测试没有解决

**Comment by jiangtiandao** [comment]
游戏安装目录下\saves\training文件夹下有A_VesselConstruction文件夹时 会卡住 删除文件夹即可

**Comment by TimChen44** [comment]
@jiangtiandao 是A_VesselConstruction文件夹呢还是A_VesselConstruction文件？

**Comment by jiangtiandao** [comment]
文件夹

**Comment by TimChen44** [comment]
奇怪，这里不是有一个这样名字的文件么？什么情况！如果确定这个文件夹不是汉化造成的，那我这个问题依旧保持关闭，不开启了。

**Comment by jiangtiandao** [comment]
\saves\training下有A_VesselConstruction.sfs文件 是教程存档 被汉化过
无论汉化与否一旦进入教程 就会生成A_VesselConstruction文件夹 里面是教程的存档
这时再次进入教程就会卡死  可能与汉化有关 不确定

**Comment by pitwam** [comment]
该问题已经找到，删除zh.xml文件里的  <string id="44151"><![CDATA[指挥舱1型]]></string>解决
使用未汉化的任务文件，任务运行正常，但用汉化后的任务文件就无法进入任务。
@jiangtiandao @TimChen44

**Comment by cxqclz** [comment]
第二句话没看懂，是说生涯模式里的任务有问题，还是说这段修复以后无法进入任务的bug已解决？

**Comment by cxqclz** [comment]
第二句话没看懂，是说生涯模式里的任务有问题，还是说这段修复以后无法进入任务的bug已解决？

**Comment by cxqclz** [comment]
第二句话没看懂，是说生涯模式里的任务有问题，还是说这段修复以后无法进入任务的bug已解决？@pitwam

**Comment by cxqclz** [comment]
第二句话没看懂，是说生涯模式里的任务有问题，还是说这段修复以后无法进入任务的bug已解决？@pitwam

**Comment by cxqclz** [comment]
第二句话没看懂，是说生涯模式里的任务有问题，还是说这段修复以后无法进入任务的bug已解决？@pitwam

**Comment by cxqclz** [comment]
第二句话没看懂，是说生涯模式里的任务有问题，还是说这段修复以后无法进入任务的bug已解决？@pitwam

**Comment by jiangtiandao** [comment]
@pitwam   只要有建造飞船教程之前玩过的存档就卡住不能动并不是汉化任务文件A_VesselConstruction.sfs的锅
经查明 是翻译了 <string id="52577" noT="1"><![CDATA[flight]]></string>导致存档文件
perisistent.sfs中出现航线 = 0所致

**Comment by pitwam** [comment]
@cxqclz 上班没有时间上网，刚忙完。这里提交的问题是第一个教程的BUG。
我第一次发现问题提交的情况是：打开第一个教程后，对话让放置指令仓，但左边空空的什么也没有，退出选项等等选项都是暗的，什么都点不到，只能强制退出。但没有汉化前是有个指令仓可提供选择。
找了几天zh.xml文件内容，昨晚删除ID：44151后就能正常通过第一个教程了。

**Comment by pitwam** [comment]
@jiangtiandao 可能你误解了我第一次提出的BUG，那个BUG是打了汉化文件后左边没有指令仓选择（空的），退出选项等等选项都是暗的，什么都点不到。不是能看到但卡着选不到，卡着选不到是因为通过了任务，但没点退出却点了发射，弹出去后在回到教程后就出现了点不到指令仓的BUG，原版就有这个BUG，但只要是点退出，怎么摆弄都不会在卡住。
昨晚删除ID：44151后，就能通过第一个教程了。只要不是点发射，点退出的话进多少次都没问题。
后来替换上A_VesselConstruction.sfs，点进入教程就卡住了，一个空的框框，左上角有一行字，忘了是什么了。这个是新延伸的问题。至于是什么，我程序不懂，试不下去了。

**Comment by jiangtiandao** [comment]
@pitwam 没有误解啊  一个空的框框，左上角有一行字 的确是因为 A_VesselConstruction.sfs出了问题
少了一个字段名称 Description=  不过我已经修复了 
你的repo没有更新 拿旧的A_VesselConstruction.sfs去覆盖自然出了问题 我这里测试正常

**Comment by jiangtiandao** [comment]
还发现了原版的bug来源
对比点击发射和退出的两个存档发现  点击发射不会更新存档版本 仍然是0.21.0 并且比正常退出少了两行
		statename = conclusion
		complete = True

**Comment by pitwam** [comment]
用的是第七个汉化版本，我以为是更新过的。

**Comment by jiangtiandao** [comment]
@pitwam  bug是我5天之前修复的  0.7是6天前发布的

**Comment by pitwam** [comment]
上图直观一点。
BUG
![1](https://cloud.githubusercontent.com/assets/12621656/8018563/17dec870-0c56-11e5-8330-a7d05adfd80c.jpg)
删除汉化文件zh.xml相关内容
![2](https://cloud.githubusercontent.com/assets/12621656/8018566/274bf314-0c56-11e5-9a4c-6a2cb81816a9.jpg)
解决BUG
![3](https://cloud.githubusercontent.com/assets/12621656/8018567/2df1ec82-0c56-11e5-9f31-05a35ec77196.jpg)
下面这个原版也会出现的BUG
![4](https://cloud.githubusercontent.com/assets/12621656/8018568/2e1bc4c6-0c56-11e5-8fb3-e3a9996b4817.jpg)

**Comment by pitwam** [comment]
上面这个BUG和A_VesselConstruction.sfs没有关系。

**Comment by jiangtiandao** [comment]
@pitwam  第一个bug昨天接到反馈已经修复  第二个找到了原因 不过得找squad

**Comment by pitwam** [comment]
@jiangtiandao 辛苦了。
