### ISSUE TITLE
替换Assembly-CSharp.dll之后 游戏无法启动

### ISSUE THREAD

**Issue by jiangtiandao** [TimChen44/KSP_zh#5]
将/resource 文件夹下全部内容覆盖到游戏目录下之后
打开KSP.exe 黑屏无响应 KSP.log无内容

系统信息（来自 KSP.log)
Kerbal Space Program - 1.0.2.842 (WindowsPlayer) Steam

OS: Windows 8.1  (6.3.9600) 64bit
CPU: Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz (8)
RAM: 8075
GPU: NVIDIA GeForce GT 650M (1985MB)
SM: 30 (Direct3D 9.0c [nvumdshim.dll 9.18.13.4725])
RT Formats: ARGB32, Depth, ARGBHalf, RGB565, Default, DefaultHDR, ARGBFloat, RGFloat, RGHalf, RFloat, RHalf, R8

**Comment by TimChen44** [comment]
你复制的是releases版本呢还是源代码的版本，看一下/resource下面有没有DTS_zh.dll文件

**Comment by jiangtiandao** [comment]
换release版本解决
