### ISSUE TITLE
30, 2015版本载入到某个组件时被卡住

### ISSUE THREAD

**Issue by ahh233** [TimChen44/KSP_zh#50]
载入条卡在\GameData\Squad\Parts\Aero\airIntakeRadialXM-G50\airIntakeRadialXM-G50\airScoop
产生错误的组件airScoop（XM-G50径向进气口）
文件airIntakeRadialXM-G50的内容
PART
{
	name = airScoop
	module = Part
	author = NovaSilisko
	mesh = model.mu
	rescaleFactor = 1
	node_attach = 0.0, 0.3370661, 0.0, 0.0, 1.0, 0.0
	TechRequired = aviation
	entryCost = 4500
	cost = 1000
	category = Aero
	subcategory = 0
	title = XM-G50 Radial Air Intake
	manufacturer = Vac-Co Advanced Suction Systems
	description = A must-have for air breathing engines, this intake duct will pull in outside air to run turbine engines on, as long as there is any outside air to begin with, of course. Warranty does not cover engine flame-outs or any objects, inanimate or otherwise, sucked in by the intake.
	attachRules = 0,1,0,0,0
	mass = 0.01
	thermalMassModifier = 4.0 // the dang things are light, so 3200 kJ/tonne-K
	// heatConductivity = 0.06 // half default
	dragModelType = default
	maximum_drag = 0.2
	minimum_drag = 0.2
	angularDrag = 1
	crashTolerance = 80
	breakingForce = 200
	breakingTorque = 200
	maxTemp = 2000 // = 5000
	bulkheadProfiles = srf
	MODULE
	{
		name = ModuleResourceIntake
		resourceName = IntakeAir
		checkForOxygen = true
		area = 0.006
		intakeSpeed = 10
		intakeTransformName = Intake
	}
	RESOURCE
	{
		name = IntakeAir
		amount = 0.6
		maxAmount = 0.6
	}
}
汉化组可以看看最近汉化了里面的哪个词条？

**Comment by TimChen44** [comment]
每次汉化内容不少，现在测试人手紧缺，你可不可以顺带帮我做一下bug定位，方法很简单，就是成批删除zh.xml中的词条，直到删除那个词条后问题解决了，再把这个出挑的id反馈回来。

**Comment by jiangtiandao** [comment]
建议使用二分法查找简单快捷

**Comment by TimChen44** [comment]
以修复

**Comment by yybl** [comment]
本来这个星期想帮忙测试的，结果另一个游戏服务器端大更新，最近一直都在忙那边的事情。
