### ISSUE TITLE
Kerbal11场景下 相机飘离飞船

### ISSUE THREAD

**Issue by jiangtiandao** [TimChen44/KSP_zh#58]
查看日志发现好多日志都被汉化了      本来能看的现在完全看不懂
还是一堆Null reference

**Comment by TimChen44** [comment]
日志被汉化是肯定的，应为只要是一个文本字符串在游戏中任何地方是公用的，至于一堆Null reference需要找BUG了。

**Comment by jiangtiandao** [comment]
和 #62 一起被修复
