### ISSUE TITLE
VAB左下角的合同情况和飞船基本信息翻译之后不显示

### ISSUE THREAD

**Issue by jiangtiandao** [TimChen44/KSP_zh#60]
推测是缺少字体文件，不是说精简过字体么。

**Comment by TimChen44** [comment]
有些不显示是因为刷新问题，你退出VAB再进入看看那是不是显示了，这个输出汉化程序上的BUG

**Comment by jiangtiandao** [comment]
并没有恢复 而且log里面又是Null reference

**Comment by jiangtiandao** [comment]
先回滚在说 parts  length size 几个单词还好 后面还有单位 翻译了不显示不如不翻译
