### ISSUE TITLE
5~6千米时火箭飞出视野

### ISSUE THREAD

**Issue by TimChen44** [TimChen44/KSP_zh#62]
飞到5~6千米时火箭飞出视野，往天上看看到火箭尾焰，我下看看到火箭头

**Comment by jiangtiandao** [comment]
Z-MAP Satellite 会这样  KERBAL 11 场景里面也是

**Comment by cxqclz** [comment]
是所有模式，还是只有某些场景和教学？

**Comment by TimChen44** [comment]
@cxqclz 我是看到贴吧有人提出了，说以我这里加一条问题免得忘记，所以我也不知道具体情况

**Comment by yybl** [comment]
好像跟高度没关系吧？？我用飞机测试的时候。过一段时间后，当飞机发生震动 （我感觉是震动） 的时候就 出现 飞机 偏离 视野中心点了，每次偏离持续累加，就会再也看不见，。。。

**Comment by pitwam** [comment]
已知和挂载的部件有关：神密的粘液罐，科研舱ＳＣ－9001，ＤＴＳ－Ｍ１通信天线。这几个测试只要挂在火箭或飞机上就会出现镜头脱离，火箭飞出视野。

**Comment by pitwam** [comment]
神密的粘液罐，科研舱ＳＣ－9001，这两个部件还有一个ＢＵＧ，在建造用部署有打开动作，但在外面用科研就没有打开动作。但宇航员出舱后在用部署也有打开动作。

**Comment by pitwam** [comment]
出现ＢＵＧ同时有问题的部件消失了，对，就是不见了。

**Comment by Rioxun** [comment]
同样的 刚开始以为是mod 的问题 后来发现只要装了对接口各种型号 只要是对接口 就会出现飞船飞出视野的现象

**Comment by jiangtiandao** [comment]
已经修复
