### ISSUE TITLE
发现一个很有意思的BUG

### ISSUE THREAD

**Issue by pitwam** [TimChen44/KSP_zh#67]
科研舱SC－9001，在建造模式点布置可以正常打开关闭，到外面就不动了。另外，如果放在指令舱下面，固定科研舱，到发射场，还没发射，指令舱就掉下来了。
![1](https://cloud.githubusercontent.com/assets/12621656/8019119/d796f6dc-0c70-11e5-8bd0-d01e15522c17.jpg)
![2](https://cloud.githubusercontent.com/assets/12621656/8019118/d7969ea8-0c70-11e5-8729-4fc91c078976.jpg)

**Comment by pitwam** [comment]
如果这样
![11](https://cloud.githubusercontent.com/assets/12621656/8019137/84842cc0-0c71-11e5-9824-c026b5f55585.jpg)
![12](https://cloud.githubusercontent.com/assets/12621656/8019138/8485affa-0c71-11e5-8c05-aa9a37764a2c.jpg)
![13](https://cloud.githubusercontent.com/assets/12621656/8019139/84b0f0fc-0c71-11e5-90a1-b26c72c8ea82.jpg)

**Comment by jiangtiandao** [comment]
在建造模式点布置可以正常打开关闭，到外面就不动了 原版同样有 怀疑不是bug 是故意设置的
掉下来可能是汉化原因

**Comment by pitwam** [comment]
@jiangtiandao BUG已找到，是翻译了zh.xml文件里ＩＤ134604的内容，删除后部件打开正常了，也不会掉落了，可能一并解决了相机漂移的ＢＵＧ。
