### ISSUE TITLE
沙盒模式下(不知道生存模式是不是也同样)雷达站中无法删除和重新控制飞行器

### ISSUE THREAD

**Issue by diqiuguying** [TimChen44/KSP_zh#7]
除了无法删除和控制飞行器外,星球描述的显示和切换貌似也有问题..

**Comment by diqiuguying** [comment]
对了,是第二版 1.0.2.842 版本的汉化

**Comment by TimChen44** [comment]
应该是zh.xml翻译中修改了一些不能动的东西，问题记下，以后找bug是会验证的。

**Comment by diqiuguying** [comment]
哦,原来是这样啊 = =
那这个issue应该可以关闭了~~~

**Comment by TimChen44** [comment]
不用关闭啊，等问题结局了在关闭，不然时间久了就不记得这个问题了。

**Comment by TimChen44** [comment]
经过验证，已经没有这个问题
