### ISSUE TITLE
载入存档后科研点数、声望、任务完成数目等被重置的问题

### ISSUE THREAD

**Issue by cxqclz** [TimChen44/KSP_zh#76]
打开debug里看到的，contractdefs无法读取satelite.science.basereward数据，并重置为**
有一排，大概十几项，可能是某个键值被汉化造成的，正在查找

**Comment by cxqclz** [comment]
![c2436e6034a85edfd8545fa64c540923df5475c9](https://cloud.githubusercontent.com/assets/12233155/8030491/d7148d02-0df9-11e5-83d1-4ae9d69d97cd.jpg)

**Comment by cxqclz** [comment]
词条里有一些带有符号的是变量，翻译会引起数据丢失，举例：  
<string id="463283"><![CDATA[>Next Hire: £ ]]></string>
  <string id="463312"><![CDATA[Next Hire: £ ]]></string>
呃……这两条只有一条会显示，翻译之后貌似显示有些问题，所以我回滚了……
这两条是宇航员中心，下次招募时间的显示，£显示的是时间，还有执行任务的星球，是用@作为变量，比如
  <string id="223967"><![CDATA[我们需要确认一些在@ 内部发生的理论。前往那里然后获取一份加速度数据。]]></string>
但是，在任务奖励那里，带有£的，有大概6条，都被汉化了，我认为问题可能出在这里，
  <string id="195221"><![CDATA[<#]]></string>
  <string id="195226"><![CDATA[>资金 -]]></string>
  <string id="195235"><![CDATA[>© -]]></string>
  <string id="195244"><![CDATA[>声誉 -]]></string>
  <string id="195558"><![CDATA[<#B4D455>资金 -]]></string>
  <string id="195581"><![CDATA[<#E0D503>声誉 -]]></string>
我我现在电脑跑不动KSP，谁帮忙测试回滚下，看看是不是这几个词条？

**Comment by jiangtiandao** [comment]
并不是以上猜测条目引发的问题 经手动二分查找发现
这两条是罪魁祸首
  string id="111786"><![CDATA[科研模式]]></string
  string id="111801"><![CDATA[生涯模式]]></string

**Comment by jiangtiandao** [comment]
光删除2条还是有bug 不过zh.xml里面只有这两个条目之一的时候也有bug
看来这个bug 还涉及其他条目
@cxqclz

**Comment by jiangtiandao** [comment]
@cxqclz 
找到了第二个条目
  string id="205989"><![CDATA[基地]]></string

**Comment by jiangtiandao** [comment]
还发现有趣的现象  汉化某个条目之后 debug菜单里面
多出了一堆按钮 +1科研等等

**Comment by TimChen44** [comment]
哇，修复速度好快，好给力啊。。。。。

**Comment by jiangtiandao** [comment]
@TimChen44 
修改汉化bug就是搬砖性质
VAB文本才是硬活
那个修复完估计可以出用户预览版了
