### ISSUE TITLE
TechTree.cfg中缺少cost data，应该添加数据还是删除条目？

### ISSUE THREAD

**Issue by cxqclz** [TimChen44/KSP_zh#79]
【R&D tech start】Tech node did not contain cost data.Looking for node in TechTree.cfg
图片上传失败，看看是文件里需要修改什么吗

**Comment by TimChen44** [comment]
@cxqclz 先删除TechTree.xml看看是否恢复正常，如果依旧不正常，那么依旧删除zh.xml中的汉化条目，直到找到某条被删除后游戏正确

**Comment by cxqclz** [comment]
![error2](https://cloud.githubusercontent.com/assets/12233155/8080726/740cdc2e-0fa1-11e5-8976-3cf1e5ea0101.jpg)

this massage should not appear again for this node。
不再出现哎咋办，没法检测啊

**Comment by jiangtiandao** [comment]
我修复了 #76 之后出现过一次 之后再也没有 要不开个新存档试试？
@cxqclz

**Comment by jiangtiandao** [comment]
开新存档仍然存在 删除 TechTree.xml同样存在
