### ISSUE TITLE
在设计界面的DEBUG中提示大量错误

### ISSUE THREAD

**Issue by TimChen44** [TimChen44/KSP_zh#80]
![screenshot1](https://cloud.githubusercontent.com/assets/7581981/8060636/18462060-0ef9-11e5-9c15-8f8cc75ca4fe.png)

**Comment by cxqclz** [comment]
会产生什么实际的效果呢……

**Comment by TimChen44** [comment]
不知道会有什么效果，只要进入编辑界面就不停的出现这个错误，有错误肯定有问题，其实也不用管他有什么实际效果，直接看debug来确定是否已经修复就好了。

**Comment by jiangtiandao** [comment]
这里没有办法复现这个bug

**Comment by cxqclz** [comment]
不能复现？意思是说进去一次，再进去就没有吗？可是我试过，进去组装中心还是机库都会出现的

**Comment by jiangtiandao** [comment]
@cxqclz  是什么模式呢？

**Comment by TimChen44** [comment]
我是在生涯模式中看到的。

**Comment by cxqclz** [comment]
同生涯模式

**Comment by cxqclz** [comment]
![default](https://cloud.githubusercontent.com/assets/12233155/8145013/342b8aee-1229-11e5-8c41-9066a7e206df.jpg)

把中文全部删掉依然会有这个提示，但是你的那个错误提示没有了，有中文的时候也没有。所以……可能是修其他bug的时候修掉了
