### ISSUE TITLE
合同标题显示不全和任务提示不能换行的问题

### ISSUE THREAD

**Issue by cirenyifeng** [TimChen44/KSP_zh#84]
![qq 20150611133645](https://cloud.githubusercontent.com/assets/12840572/8100636/271a3e5c-1041-11e5-8036-c1e9de914003.png)
![qq 20150611133703](https://cloud.githubusercontent.com/assets/12840572/8100638/271df6a0-1041-11e5-92c8-df3d10e359b6.png)
![qq 20150611133713](https://cloud.githubusercontent.com/assets/12840572/8100640/271fbc38-1041-11e5-906a-662c439bcb6c.png)
![qq 20150611133754](https://cloud.githubusercontent.com/assets/12840572/8100639/271f89b6-1041-11e5-9b7d-c229bc7214da.png)
![qq 20150611133831](https://cloud.githubusercontent.com/assets/12840572/8100637/271d6de8-1041-11e5-86b4-8382c7cf6936.png)

**Comment by cirenyifeng** [comment]
![Uploading QQ截图20150611140459.png…]()
![Uploading QQ截图20150611140711.png…]()
![Uploading QQ截图20150611140252.png…]()

**Comment by cxqclz** [comment]
这几个看着是挺不舒服的，文本肯定是翻译了才会显示不出来，这个得问@Tiimchen44

**Comment by jiangtiandao** [comment]
查看log发现 替换输出的时候 中文不见了
[xFont1]Calibri12-->>cn12FL-T400

**Comment by TimChen44** [comment]
@jiangtiandao 这两天没空，过几天修复。

**Comment by cxqclz** [comment]
还有部分中文也不能显示

**Comment by cxqclz** [comment]
任务描述里的

**Comment by TimChen44** [comment]
任务不能显示问题比想象的麻烦，这些文本都在zh.xml中，但是好像任务名称文本组织哪里不支持中文，需要深入查代码，过几天空了查。

**Comment by cxqclz** [comment]
还有“执行可视探查“、”舱内报告“这几个无法正常显示，还有所有的任务完成似乎都不显示中文。

**Comment by TimChen44** [comment]
版本更迭，所有问题关闭。
