### ISSUE TITLE
游戏无故奔溃

### ISSUE THREAD

**Issue by qq823478201** [TimChen44/KSP_zh#85]
![image](https://cloud.githubusercontent.com/assets/12841159/8101262/e415d6dc-1047-11e5-8700-3f96b13a5d4e.png)
今天到现在是第三次了、多发生于太空中

**Comment by jiangtiandao** [comment]
请提供游戏安装文件夹下的KSP.LOG  和KSP_Data文件夹下的output.log

**Comment by jiangtiandao** [comment]
打开游戏到出现窗口前多次点击鼠标就会出现这种情况
查看log似乎是分辨率不匹配什么的 原因很复杂 估计修复不了
@qq823478201 
点开游戏不要急 慢慢等 等到游戏窗口出来就可以了

**Comment by TimChen44** [comment]
@jiangtiandao 可能是程序启动时我载入汉化资源直接堵塞了UI线程，系统就认为是程序没有响应。这问题以后我看看能不能修复。
