### ISSUE TITLE
登陆mum时视角和视线中心偏移

### ISSUE THREAD

**Issue by cxqclz** [TimChen44/KSP_zh#87]
来自贴吧：mun着陆的时候 视角中心会突然移动，离飞船越来越远，而且飞船旋转的中心也跟着视角远离，重新载入后恢复正常

**Comment by cxqclz** [comment]
还有人反馈的出入大气层、出仓时也会有

**Comment by cxqclz** [comment]
还有人反馈的出入大气层、出仓时也会有

**Comment by pitwam** [comment]
做了几次实验，结果这个BUG还是和部件消失有关。用游戏自带飞船“Kerbal X”飞往MUN，在接近MUN过程中，原装火箭上的梯子（LV）消失，随后视角偏离火箭。在建造时把这个梯子重装一下，偏离的问题就没出现了。
实验比较片面。
会消失的部件：
![360 20150703161555540](https://cloud.githubusercontent.com/assets/12621656/8495326/4f66df90-219f-11e5-9b5a-548beaa4f004.jpg)

**Comment by jiangtiandao** [comment]
fixed in pull request #115
