### ISSUE TITLE
沙盒模式的VBA无法读取飞船存档，生涯模式无此问题

### ISSUE THREAD

**Issue by cxqclz** [TimChen44/KSP_zh#94]
正在测试

**Comment by cxqclz** [comment]
SPH没有问题，删除中文后依然无法打开。贴吧有人说删除有“+”号的文件可以解决，但是我没有找到

**Comment by cxqclz** [comment]
我是想去测试月球上会视点偏移的bug，但我现在压根去不了月球

**Comment by ahh233** [comment]
在生涯模式也会出现，只要选择允许使用游戏自带的飞船设计，应该是读取自带飞船这一块的问题。

**Comment by pitwam** [comment]
删除Rover + Skycrane.craft这个存档文件就正常了，文件在目录Ships\VAB文件夹里。
是下面这个飞船。这个问题可以关闭。
![rover skycrane](https://cloud.githubusercontent.com/assets/12621656/8396036/17a2571e-1dc7-11e5-84fc-3ce7ce94f5c1.png)
