### ISSUE TITLE
老存档的初始任务和科技树被重置

### ISSUE THREAD

**Issue by cxqclz** [TimChen44/KSP_zh#95]
进游戏后老存档的科技树被重置，任务里的＂发射第一个载具＂任务变为未执行

**Comment by cxqclz** [comment]
但是我测试又是好的呢……有些人有，什么鬼？

**Comment by TimChen44** [comment]
@cxqclz  每个版本对老存档不保证兼容，切记。我举个例子说明原因把。
假如原始程序某个数据存在apple节点（可以理解为文件夹）中，然后这个名字被我们汉化成了苹果，然后游戏会把这些数据存在苹果节点中。这个时候你打开老存档程序会在苹果节点中找数据，那么怎么也找不到之前存在apple中的数据啦。

**Comment by cxqclz** [comment]
已经修复，见刚才上传的bugfix，好诡异的键值位置
